services:
  backend:
    build: .
    container_name: lexbancario_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - rag_net

  frontend:
    build: .
    container_name: lexbancario_frontend
    command: streamlit run app_streamlit.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000/api/consultar
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    networks:
      - rag_net

networks:
  rag_net:
    driver: bridge
