-- ============================================================
-- Esquema completo de un proyecto limpio, listo para `aplicar_sql.py`.
--
-- Antes de existir `coleccion_id`, esta tabla era de un solo tenant y la
-- funcion `match_normativa` buscaba sobre toda la tabla. Sin columna de
-- tenant no hay forma de aislar nada: cualquier consulta ve el corpus
-- entero. Este archivo es el que hay que ejecutar para desplegar desde
-- cero; el orden importa, porque la tabla se crea antes que el indice y
-- la funcion antes que los permisos.
--
-- El orden de los indices tiene una lectura. `..._coleccion_embedding_idx`
-- empieza por `coleccion_id`, asi que el filtro de tenant se resuelve con
-- esa sola estructura; el B-Tree simple en `coleccion_id` queda redundante
-- para este caso de uso, y se deja solo porque tambien sirve para contar.
-- El HNSW va al final a proposito: con pocas filas PostgreSQL elige
-- secuencial y no lo usaria. Es capacidad futura, no una ganancia actual.
-- ============================================================

create extension if not exists vector;

-- ---------------------------------------------------------------------
-- 1. Tabla
-- ---------------------------------------------------------------------
create table if not exists normativa_bancaria (
  id bigint generated by default as identity primary key,
  documento_origen text not null,
  organismo text,
  tipo_norma text,
  jerarquia text,
  articulo_ref text,
  contenido text,
  coleccion_id varchar(50) not null default 'asfi_rnsf',
  embedding vector(768)
);

-- Un fragmento no pertenece a dos colecciones a la vez. Sin este
-- constraint, un INSERT con coleccion_id equivocado pasaria inadvertido y
-- el aislamiento se romperia en silencio.
alter table normativa_bancaria
  drop constraint if exists normativa_bancaria_coleccion_no_nula;
alter table normativa_bancaria
  add constraint normativa_bancaria_coleccion_no_nula
  check (coleccion_id is not null and length(coleccion_id) > 0);

-- ---------------------------------------------------------------------
-- 2. Indices
-- ---------------------------------------------------------------------
-- Filtro de tenant. El prefijo `coleccion_id` permite que el filtro se
-- resuelva en indice y recorte el conjunto ANTES de ordenar por distancia.
create index if not exists normativa_bancaria_coleccion_embedding_idx
  on normativa_bancaria (coleccion_id, documento_origen);

-- Para inventarios y consultas administrativas por coleccion.
create index if not exists normativa_bancaria_coleccion_idx
  on normativa_bancaria (coleccion_id);

-- Busqueda vectorial aproximada. Con el volumen actual PostgreSQL
-- probablemente elija un Seq Scan: es capacidad preparada para cuando las
-- colecciones crezcan, no una aceleracion medida hoy.
create index if not exists normativa_bancaria_embedding_idx
  on normativa_bancaria
  using hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------
-- 3. RPC de busqueda aislada
--
-- El parametro lleva prefijo `p_` a proposito. Un parametro sin prefijar
-- que coincida con el nombre de una columna genera ambiguedad de ambito
-- en PL/pgSQL y puede romper el filtro en silencio: el error grave no es
-- que falle, es que deje de filtrar y todos los tenants vean todo.
--
-- SECURITY DEFINER con search_path fijado: la funcion se ejecuta con los
-- permisos del dueno, asi que el search_path debe cerrarse o un objeto
-- malicioso en el esquema public podria ejecutarse en su lugar.
-- ---------------------------------------------------------------------
create or replace function match_normativa_coleccion(
  query_embedding  vector(768),
  match_threshold  float,
  match_count      int,
  p_coleccion_id   varchar(50)
)
returns table (
  id               bigint,
  documento_origen text,
  organismo        text,
  tipo_norma       text,
  jerarquia        text,
  articulo_ref     text,
  contenido        text,
  coleccion_id     varchar(50),
  similarity       float
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  return query
    select
      nb.id,
      nb.documento_origen,
      nb.organismo,
      nb.tipo_norma,
      nb.jerarquia,
      nb.articulo_ref,
      nb.contenido,
      nb.coleccion_id,
      1 - (nb.embedding <=> query_embedding) as similarity
    from normativa_bancaria nb
    where nb.coleccion_id = p_coleccion_id
      and 1 - (nb.embedding <=> query_embedding) > match_threshold
    order by nb.embedding <=> query_embedding
    limit match_count;
end;
$$;

comment on function match_normativa_coleccion(vector, float, int, varchar) is
  'Busqueda vectorial aislada por coleccion. El filtro coleccion_id se '
  'evalua sobre el indice, garantizando cero contaminacion cruzada.';

-- ---------------------------------------------------------------------
-- 4. Inventario de colecciones
-- ---------------------------------------------------------------------
create or replace function listar_colecciones()
returns table (
  coleccion_id      varchar(50),
  total_fragmentos   bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select coleccion_id, count(*)
  from normativa_bancaria
  group by coleccion_id
  order by coleccion_id;
$$;

-- ---------------------------------------------------------------------
-- 5. Permisos
--
-- `anon` y `authenticated` son los roles que usa PostgREST. Se les da
-- EXECUTE y nada mas: no necesitan acceso directo a la tabla, y darles
-- SELECT sobre ella abriria la puerta a saltarse el filtro de la RPC.
-- El acceso a datos pasa por la RPC, que es donde esta el aislamiento.
-- ---------------------------------------------------------------------
revoke all on function match_normativa_coleccion(vector, float, int, varchar) from public;
revoke all on function listar_colecciones() from public;

grant execute on function match_normativa_coleccion(vector, float, int, varchar) to anon, authenticated;
grant execute on function listar_colecciones() to anon, authenticated;