create extension if not exists vector;

create table if not exists normativa_bancaria (
  id bigint generated by default as identity primary key,
  documento_origen text not null,
  organismo text,
  tipo_norma text,
  jerarquia text,
  articulo_ref text,
  contenido text,
  embedding vector(768)
);

create index if not exists normativa_bancaria_embedding_idx
  on normativa_bancaria
  using hnsw (embedding vector_cosine_ops);

create or replace function match_normativa(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  documento_origen text,
  organismo text,
  tipo_norma text,
  jerarquia text,
  articulo_ref text,
  contenido text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    nb.id,
    nb.documento_origen,
    nb.organismo,
    nb.tipo_norma,
    nb.jerarquia,
    nb.articulo_ref,
    nb.contenido,
    1 - (nb.embedding <=> query_embedding) as similarity
  from normativa_bancaria nb
  where 1 - (nb.embedding <=> query_embedding) > match_threshold
  order by nb.embedding <=> query_embedding
  limit match_count;
end;
$$;